folds : [
  ["2014-12-31", ["2015-1-01", "2015-3-31"]],
  ["2015-3-31", ["2015-4-01", "2015-6-30"]],
  ["2015-6-30", ["2015-7-01", "2015-9-30"]],
  ["2015-9-30", ["2015-10-01", "2015-12-31"]]
]

codify_cols: [
  "articleID", "colorCode", "sizeCode",
  "customerID", "paymentMethod", "voucherID",
  "deviceID", "productGroup"
]

codify_cols_group: [
  ["articleID", "colorCode"],
  ["articleID", "sizeCode"],
  ["articleID", "sizeCode", "colorCode"],
  ["productGroup", "colorCode"],
  ["productGroup", "sizeCode"],
  ["productGroup", "sizeCode", "colorCode"],
  ["productGroup", "month"],
  ["productGroup", "fortnight"]
]
