folds : [
  ["2014-12-31", ["2015-1-01", "2015-3-31"]],
  ["2015-3-31", ["2015-4-01", "2015-6-30"]],
  ["2015-6-30", ["2015-7-01", "2015-9-30"]],
  ["2015-9-30", ["2015-10-01", "2015-12-31"]]
]

codify_cols: [
  "articleID", "colorCode", "sizeCode",
  "customerID", "paymentMethod", "voucherID",
  "deviceID", "productGroup"
]

codify_cols_group: [
  ["articleID", "colorCode"],
  ["articleID", "sizeCode"],
  ["articleID", "sizeCode", "colorCode"],
  ["productGroup", "colorCode"],
  ["productGroup", "sizeCode"],
  ["productGroup", "sizeCode", "colorCode"],
  ["productGroup", "month"],
  ["productGroup", "fortnight"]
]


learners : [
      {
        "learner": XGBClassifier,
        "params": {
            "learning_rate": [0.1],
            "colsample_bytree": [0.15, 0.25, 0.5, 0.75, 1],
            "colsample_bylevel": [1],
            "max_depth": [3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 25],
            "gamma": [0, 0.01, 0.05, 0.1, 0.25, 0.5],
            "subsample": [0.5, 0.75, 1],
            "min_child_weight": [1, 5, 10, 15, 25, 50, 100],
            "base_score": [0.52]
            },
        "control_params": {
            "n_estimators": 1000
        }
    },
    {
        "learner": RandomForestClassifier,
        "params": {
            "max_depth": [20, 25, None],
            "max_features": ["auto", 0.25, 0.5, 0.75, 1],
            "min_weight_fraction_leaf": [0, 0.0001, 0.001, 0.01],
            "bootstrap": [True, False]
            },
        "control_params": {
            "n_estimators": 1000,
            "n_jobs": -1
        },
        "fit_params": {
            "esr": 50
        }
    },
    {
        "learner": ExtraTreesClassifier,
        "params": {
            "max_depth": [20, 25, None],
            "max_features": ["auto", 0.25, 0.5, 0.75, 1],
            "min_weight_fraction_leaf": [0, 0.0001, 0.001, 0.01],
            "bootstrap": [True, False]
            },
        "control_params": {
            "n_estimators": 1000,
            "n_jobs": -1
        },
        "fit_params": {
            "esr": 50
        }
    },
]
